// <auto-generated />
namespace Buildy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedonetomanyRelationshipsonPSUMBRAMStorage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedonetomanyRelationshipsonPSUMBRAMStorage));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061251220_Added one to many Relationships on PSU , MB , RAM , Storage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
